# encoding: UTF-8

require "thor"
require "faker"
require "os"
require "yaml"

module ThemeJuice
end

require_relative "theme-juice/version"
require_relative "theme-juice/env"
require_relative "theme-juice/project"
require_relative "theme-juice/util"
require_relative "theme-juice/io"
require_relative "theme-juice/config"
require_relative "theme-juice/task"
require_relative "theme-juice/tasks/entry"
require_relative "theme-juice/tasks/vm"
require_relative "theme-juice/tasks/create_confirm"
require_relative "theme-juice/tasks/location"
require_relative "theme-juice/tasks/theme"
require_relative "theme-juice/tasks/repo"
require_relative "theme-juice/tasks/dot_env"
require_relative "theme-juice/tasks/hosts"
require_relative "theme-juice/tasks/nginx"
require_relative "theme-juice/tasks/vm_plugins"
require_relative "theme-juice/tasks/vm_location"
require_relative "theme-juice/tasks/vm_customfile"
require_relative "theme-juice/tasks/database"
require_relative "theme-juice/tasks/landrush"
require_relative "theme-juice/tasks/synced_folder"
require_relative "theme-juice/tasks/dns"
require_relative "theme-juice/tasks/wp_cli"
require_relative "theme-juice/tasks/create_success"
require_relative "theme-juice/tasks/delete_success"
require_relative "theme-juice/tasks/vm_provision"
require_relative "theme-juice/tasks/vm_restart"
require_relative "theme-juice/tasks/list"
require_relative "theme-juice/command"
require_relative "theme-juice/commands/create"
require_relative "theme-juice/commands/delete"
require_relative "theme-juice/commands/deploy"
require_relative "theme-juice/cli"
